### ISSUE TITLE
Needs EGL permission?

### ISSUE THREAD

**Issue by fbruetting** [flathub/org.gnome.meld#10]
With the current version v3.18.3 on F29SB, I encountered this error after starting it with two files:

```
libEGL warning: wayland-egl: could not open /dev/dri/card0 (file or directory not found)
```

Still, it worked, but maybe this leads to some issues?

**Comment by bilelmoussaoui** [comment]
Any ideas @kaiw ?

**Comment by nedrichards** [comment]
Run on the CLI with --device=dri which should enable graphics acceleration to be used. If required generally this can be added to the finish-args

**Comment by fbruetting** [comment]
Ok, I could track that down to happen exactly when I open the GTK inspector.

**Comment by bilelmoussaoui** [comment]
@fbruetting 3.19 is a dev release, see here https://github.com/flathub/org.gnome.meld/pull/6#issuecomment-426223041

**Comment by kaiw** [comment]
I don't know what the standard packaging policy here is, but since this only happens when opening the GTK+ inspector... surely this is either a generic requirement for all apps using GTK+, or opening the inspector is just not supported?

For what it's worth, I don't know of any reason that Meld would be special in this way.

**Comment by TingPing** [comment]
You can add the dri permission, its pretty standard. I do find it very odd that the inspector needs OpenGL though.
